framework:
    notifier:
        chatter_transports:
            centrifugo: '%env(CENTRIFUGO_DSN)%'
        texter_transports:
        channel_policy:
            urgent: ['centrifugo']
            high: ['centrifugo']
            medium: ['centrifugo']
            low: ['centrifugo']
        admin_recipients:
            - { email: admin@example.com }
