framework:
    notifier:
        chatter_transports:
            centrifugal: '%env(CENTRIFUGAL_DSN)%'
        texter_transports:
        channel_policy:
            urgent: ['centrifugal']
            high: ['centrifugal']
            medium: ['centrifugal']
            low: ['centrifugal']
        admin_recipients:
            - { email: admin@example.com }
