version: "3"

server:
    command: "php public/index.php"
    env:
        - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
    address: 0.0.0.0:8080
    middleware: [ "static", "gzip" ]
    pool:
        debug: false
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]

logs:
    mode: production
    channels:
        http:
            level: debug
        server:
            level: info
            mode: raw
        metrics:
            level: error

service:
    app_async:
        service_name_in_log: true
        timeout_stop_sec: 60
        remain_after_exit: true
        restart_sec: 1
        process_num: 3
        command: bin/console messenger:consume async --no-ansi -v --limit=100 --time-limit=86400
