services:
    app:
        image: ghcr.io/taranovegor/noto:latest
        container_name: noto_app
        ports:
            - "8080:8080"
        restart: unless-stopped
#        environment:
#            - APP_ENV
#            - APP_SECRET
#            - DEFAULT_URI
#            - DATABASE_URL
