services:
    app:
        image: ghcr.io/taranovegor/noto:latest
        container_name: noto_app
        ports:
            - "8080:8080"
        depends_on:
            - db
        restart: unless-stopped
