services:
    app:
        build:
            target: development
        volumes:
            - ./:/app
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=localhost}
        depends_on:
            - db

    db:
        image: postgres:18
        container_name: noto_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: noto
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${DB_PASSWORD:-ChangeMe}
        volumes:
            - db_data:/var/lib/postgresql
        restart: unless-stopped

volumes:
    db_data:
