<?php

namespace App\Dto\Extraction;

use App\Enum\Extraction\FragmentStatus;
use App\Enum\Extraction\FragmentType;

/**
 * A single piece of extracted content tracked on an Extraction.
 *
 * A fragment is one of two shapes:
 *  - reference: attachment bytes (image, document) handed to the final model by
 *    URL — known at planning time, so {@see FragmentStatus::Done} immediately;
 *  - produced: content generated by an async worker (audio transcript) — starts
 *    {@see FragmentStatus::Pending} and is filled with a `result` later.
 *
 * Both carry the `storageKey` of their source bytes; the presigned URL is minted
 * just before use (keys are stable, presigned URLs expire).
 */
final class Fragment implements \JsonSerializable
{
    public function __construct(
        public readonly FragmentType $type,
        public readonly string $id,
        public readonly ?string $storageKey = null,
        public readonly ?string $mimeType = null,
        public readonly ?string $filename = null,
        public FragmentStatus $status = FragmentStatus::Pending,
        public ?string $result = null,
        public ?string $error = null,
    ) {
    }

    /**
     * A fragment whose bytes are handed to the model by reference (image,
     * document). Complete as soon as it is planned.
     */
    public static function reference(FragmentType $type, string $id, string $storageKey, string $mimeType, string $filename): self
    {
        return new self($type, $id, $storageKey, $mimeType, $filename, FragmentStatus::Done);
    }

    /**
     * A fragment whose content is produced later by an async worker (audio
     * transcript). The storage key points at the stored source segment.
     */
    public static function pending(FragmentType $type, string $id, string $storageKey, string $mimeType, string $filename): self
    {
        return new self($type, $id, $storageKey, $mimeType, $filename, FragmentStatus::Pending);
    }

    /**
     * A fragment that failed at planning time (e.g. unsupported file type). It is
     * excluded from the merged content but recorded for visibility.
     */
    public static function failed(FragmentType $type, string $id, string $error): self
    {
        return new self($type, $id, status: FragmentStatus::Failed, error: $error);
    }

    /**
     * @param array{type: string, id: string, storageKey?: string, mimeType?: string, filename?: string, status: string, result?: string, error?: string} $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            type: FragmentType::from($data['type']),
            id: $data['id'],
            storageKey: $data['storageKey'] ?? null,
            mimeType: $data['mimeType'] ?? null,
            filename: $data['filename'] ?? null,
            status: FragmentStatus::from($data['status']),
            result: $data['result'] ?? null,
            error: $data['error'] ?? null,
        );
    }

    /**
     * @return array{type: string, id: string, storageKey: ?string, mimeType: ?string, filename: ?string, status: string, result: ?string, error: ?string}
     */
    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type->value,
            'id' => $this->id,
            'storageKey' => $this->storageKey,
            'mimeType' => $this->mimeType,
            'filename' => $this->filename,
            'status' => $this->status->value,
            'result' => $this->result,
            'error' => $this->error,
        ];
    }
}
