api_controllers:
    resource: '../src/Controller/Api/'
    type: attribute
    prefix: /api
    name_prefix: api_

centrifugo_controllers:
    resource: '../src/Component/Centrifugo/Controller/'
    type: attribute
    prefix: /api/centrifugo
    name_prefix: api_centrifugo_

app_controllers:
    resource: '../src/Controller/App/'
    type: attribute
    prefix: /
    name_prefix: app_

mcp:
    resource: '../src/Mcp/'
    type: mcp
