api_controllers:
    resource: '../src/Controller/Api/'
    type: attribute
    prefix: /api
    name_prefix: api_

centrifugo_controllers:
    resource: '../src/Component/Centrifugo/Controller/'
    type: attribute
    prefix: /api/centrifugo
    name_prefix: api_centrifugo_

api_auth_login:
    path: /api/auth/login
    methods: [ POST ]
    name_prefix: api_auth_login

api_auth_refresh:
    path: /api/auth/refresh
    methods: [ POST ]
    name_prefix: api_auth_refresh

api_auth_logout:
    path: /api/auth/logout
    methods: [ POST ]
    name_prefix: api_auth_logout

app_controllers:
    resource: '../src/Controller/App/'
    type: attribute
    prefix: /
    name_prefix: app_

mcp:
    resource: '../src/Mcp/'
    type: mcp
