parameters:
    ai.additional_models:
        voyage-4-large:
            class: Symfony\AI\Platform\Bridge\Voyage\Voyage
            capabilities:
                - !php/const Symfony\AI\Platform\Capability::INPUT_MULTIPLE
                - !php/const Symfony\AI\Platform\Capability::EMBEDDINGS
        voyage-4:
            class: Symfony\AI\Platform\Bridge\Voyage\Voyage
            capabilities:
                - !php/const Symfony\AI\Platform\Capability::INPUT_MULTIPLE
                - !php/const Symfony\AI\Platform\Capability::EMBEDDINGS
        voyage-4-lite:
            class: Symfony\AI\Platform\Bridge\Voyage\Voyage
            capabilities:
                - !php/const Symfony\AI\Platform\Capability::INPUT_MULTIPLE
                - !php/const Symfony\AI\Platform\Capability::EMBEDDINGS

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{Dto,Entity,Exception,Kernel.php}'

    error_renderer:
        class: Symfony\Component\ErrorHandler\ErrorRenderer\SerializerErrorRenderer
        arguments:
            $format: 'json'

    ai.platform.model_catalog.voyage:
        class: Symfony\AI\Platform\Bridge\Voyage\ModelCatalog
        arguments:
            $additionalModels: '%ai.additional_models%'

    Symfony\AI\Store\Document\VectorizerInterface: '@ai.vectorizer.voyage'

    Symfony\AI\Store\StoreInterface: '@App\Service\Embedding\EmbeddingStore'

    ai.store.document.transformer.text_trim:
        class: Symfony\AI\Store\Document\Transformer\TextTrimTransformer

    ai.store.document.transformer.plain_text:
        class: App\Component\Ai\Store\Document\PlainTextTransformer

    ai.store.document.transformer.text_split:
        class: App\Component\Ai\Store\Document\TextSplitTransformer

    ai.store.document.indexable_entity_loader:
        class: App\Component\Ai\Store\Document\IndexableEntityLoader

    League\CommonMark\Environment\EnvironmentInterface:
        class: League\CommonMark\Environment\Environment

    League\CommonMark\ConverterInterface:
        class: League\CommonMark\CommonMarkConverter

    cloudflare_r2_client:
        class: 'AsyncAws\S3\S3Client'
        arguments:
            $configuration:
              {
                endpoint: '%env(CLOUDFLARE_R2_ENDPOINT)%',
                accessKeyId: '%env(CLOUDFLARE_R2_ID)%',
                accessKeySecret: '%env(CLOUDFLARE_R2_SECRET)%'
              }
            $httpClient: '@http_client'
            $logger: '@monolog.logger.s3'

    App\Component\Storage\ObjectStorage:
        arguments:
            $s3Client: '@cloudflare_r2_client'
            $bucket: '%env(CLOUDFLARE_R2_BUCKET)%'
