parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{Dto,Entity,Exception,Kernel.php}'

    error_renderer:
        class: Symfony\Component\ErrorHandler\ErrorRenderer\SerializerErrorRenderer
        arguments:
            $format: 'json'

    App\Component\Searcher\OpenApi\SearchCriteriaDescriber:
        tags:
            - nelmio_api_doc.route_describer
